language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
  - npm i webpack
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
  - npm run build-client
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: deployment-exercise-fsa
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: rSbJ1yj3KBhOl0qQVC7lXlq8ghRRB2KmTe3FLBDZCQ1MF+tMzrFptJPRQsDpdhJo76ZWPM060zfhj4fvNgYvRve2ECPZiPbzhy0KHGEmXQY7E05ygeFOnSUZ6VJMKSsrZ66PGApIww0IQKBqujokcoH5PHOejbmczSpllEO6HzcwCNMq20Dr8uLsErRXFIEH6QriBq2o4a4XWikwK3sC8K+XpQe8ZhDMIYpBZJPfhzDYNwURhueK7fJrE1izTE5dB/bR7ygqrRcCsV/2NFXKSA4xIkfk9L39qIRHMaxmGHyy5Js/XCN4g/GSaUGUWXgyixhu5xJQuqmWhjbRyLAwYGqKHGrjJS3Lp0j8UDmWacGDWY+8J5CwuYW2mIh7c1ibPlxdcz+SSODJh5vmsDrOfP+9MYQ7KPXfB0Oi1w9TzT1VE4Yxd1KqSiPKk7hWGxOtTlFtKm5i+6edhRpmUJrDuILiPY3TUYG07wVNIsMGzLEUgMB0RJZjMW7DFlPOmlKwXbtRiV3eV+tfYSB8vBqCWPRywNf62fpwc37ynv0PaV70+UuwkNAxWAWJX1c14IX9MBl96SH6YV4nKaSfgMBQhpxejJXTbAmopSbds8hbOoVyXJSPVHVGbwN1RtGo8HT60+RrQ8Ig+v8wfHo+WlLv+OMlYJyWPri3FiUej9L5P8w=
